repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
