language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py27 LATEST_GIT=1
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy-5.7.1
before_install:
    - git --version
    - |
        if [ "$LATEST_GIT" = "1" ]; then
            ./latest-git.sh
            export PATH="/tmp/git/bin:$PATH"
        fi
    - git --version
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
