language: python
python: 3.5
env: # These should match the tox env list
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py27 LATEST_GIT=1
# Special snowflake.  Our tests depend on making real commits.
before_install:
    - git config --global user.name "Travis CI"
    - git config --global user.email "user@example.com"
    - git --version
    - |
        if [ "$LATEST_GIT" = "1" ]; then
            ./latest-git.sh
            export PATH="/tmp/git:$PATH"
        fi
    - git --version
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
