language: python

python:
    - 2.6
    - 2.7

install: pip install virtualenv
script: make
# Special snowflake.  Our tests depend on making real commits.
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
